#pragma once

#define RES_FONT 101
#define RES_WARFRAME_HERO 102
#define RES_WARFRAME_ICON 103
#define RES_PUBLISHER_LOGO 104
#define RES_SOULFRAME_HERO 105
#define RES_SOULFRAME_ICON 106
#define RES_SOULFRAME_LEAF 107
#define RES_SOULFRAME_ENDCAP 108
